import re
import json

# Datos consolidados de todos los chunks vistos (resumen de marcas representativas)
raw_data = """
[ABACAVIR](https://www.vademecum.es/colombia/medicamento/1539133/abacavir)
[AMPICILINA Y SULBACTAM  FARMALOGICA 1 g/0,5 g](https://www.vademecum.es/colombia/medicamento/1539133/ampicilina-y-sulbactam-farmalogica-1-g-0-5-g-polvo-para-sol-iny-)
[ARANESP 100 mcg/0,5 ml Sol. iny.](https://www.vademecum.es/colombia/medicamento/1539064/aranesp-100-mcg-0-5-ml-sol-iny-)
[AUROPENNZ 2 g/1 g Polvo para sol. iny.](https://www.vademecum.es/colombia/medicamento/1538971/auropennz-2-g-1-g-polvo-para-sol-iny-)
[AVOSAL 1 g/0,5 g Polvo para sol. iny.](https://www.vademecum.es/colombia/medicamento/1561507/avosal-1-g-0-5-g-polvo-para-sol-iny-)
[AZACITIDINA 100 mg Liof. para sol. iny.](https://www.vademecum.es/colombia/medicamento/1558558/azacitidina-100-mg-liof-para-sol-iny-)
[ALIZAPRIDA HUMAX 50 mg/2 ml Sol. iny.](https://www.vademecum.es/colombia/medicamento/1556689/alizaprida-humax-50-mg-2-ml-sol-iny-)
[AMPICILINA  VITALIS 500 mg Polvo para sol. iny.](https://www.vademecum.es/colombia/medicamento/1539136/ampicilina-vitalis-500-mg-polvo-para-sol-iny-)
[BOTEMIB 1 mg Liof. para sol. iny.](https://www.vademecum.es/colombia/medicamento/1549398/botemib-1-mg-liof-para-sol-iny-)
[BOTOX 100 U Polvo para sol. iny.](https://www.vademecum.es/colombia/medicamento/1538693/botox-100-u-polvo-para-sol-iny-)
[BUTILBROMURO HIOSCINA RYAN 20 mg/ml Sol. iny.](https://www.vademecum.es/colombia/medicamento/1538613/butilbromuro-hioscina-ryan-20-mg-ml-sol-iny-)
[BERIGLOBINA - P 800 mg/5 ml Sol. iny.](https://www.vademecum.es/colombia/medicamento/1559022/beriglobina-p-800-mg-5-ml-sol-iny-)
[BENLYSTA 400 mg Liof. para sol. iny.](https://www.vademecum.es/colombia/medicamento/1561501/benlysta-400-mg-liof-para-sol-iny-)
[BETAMETASONA INYECTABLE X  GENFAR 8 mg/2 ml Sol. Iny.](https://www.vademecum.es/colombia/medicamento/1538800/betametasona-inyectable-x-genfar-8-mg-2-ml-sol-iny-)
[CITICOLINA  ROSBLANK 500 mg Sol. iny.](https://www.vademecum.es/colombia/medicamento/1538305/citicolina-rosblank-500-mg-sol-iny-)
[CITARABINA FRESENIUS KABI 500 mg/5 ml Sol. iny.](https://www.vademecum.es/colombia/medicamento/1560271/citarabina-fresenius-kabi-500-mg-5-ml-sol-iny-)
[CEFUROXIMA  PUNISKA 750 mg Polvo para sol. iny.](https://www.vademecum.es/colombia/medicamento/1538435/cefuroxima-puniska-750-mg-polvo-para-sol-iny-)
[CITRATO DE FENTANILO RYAN 0,05 mg/ml  Sol iny.](https://www.vademecum.es/colombia/medicamento/1538303/citrato-de-fentanilo-ryan-0-05-mg-ml-sol-iny-)
[CLORHIDRATO DE KETAMINA HOLLAND 50 mg/ml Sol. iny.](https://www.vademecum.es/colombia/medicamento/1626334/clorhidrato-de-ketamina-holland-50-mg-ml-sol-iny-)
[CELESTONE ORGANON 4 mg/1 ml Sol. iny.](https://www.vademecum.es/colombia/medicamento/1556927/celestone-organon-4-mg-1-ml-sol-iny-)
[CHORIOMON 5000 UI Liof. para sol. iny.](https://www.vademecum.es/colombia/medicamento/1538362/choriomon-5000-ui-liof-para-sol-iny-)
[CARBETOCINA  VITALIS 100 mcg/ 1 ml Sol. iny](https://www.vademecum.es/colombia/medicamento/1549367/carbetocina-vitalis-100-mcg-1-ml-sol-iny)
[CAFNEA 20 mg/1 ml Sol. iny.](https://www.vademecum.es/colombia/medicamento/1538605/cafnea-20-mg-1-ml-sol-iny-)
[CEFALOTINA 1 g Polvo para sol. iny.](https://www.vademecum.es/colombia/medicamento/1538473/cefalotina-1-g-polvo-para-sol-iny-)
[CEFAZOLINA  FARMALOGICA 1 g Polvo para sol. iny.](https://www.vademecum.es/colombia/medicamento/1538472/cefazolina-farmalogica-1-g-polvo-para-sol-iny-)
[DIFENHIDRAMINA HC LICOL 10 mg/ml Sol. iny.](https://www.vademecum.es/colombia/medicamento/1560260/difenhidramina-hc-licol-10-mg-ml-sol-iny-)
[DIPHERELINE 11,25 mg Polvo para susp.](https://www.vademecum.es/colombia/medicamento/1626226/diphereline-11-25-mg-polvo-para-susp-)
[DIPIRONA 1 g/2 ml Sol. iny.](https://www.vademecum.es/colombia/medicamento/1537756/dipirona-1-g-2-ml-sol-iny-)
[DORMIPRON INYECTABLE 15 mg Sol. iny.](https://www.vademecum.es/colombia/medicamento/1537657/dormipron-inyectable-15-mg-sol-iny-)
[DIAZEPAM BIOSANO 10 mg/2 ml Sol. iny.](https://www.vademecum.es/colombia/medicamento/1537840/diazepam-biosano-10-mg-2-ml-sol-iny-)
[DICLOFENACO BIO ESTERIL 75 mg/3 ml Sol. iny.](https://www.vademecum.es/colombia/medicamento/1571482/diclofenaco-bio-esteril-75-mg-3-ml-sol-iny-)
[DIUXOTON 20 mg/ml Sol. iny.](https://www.vademecum.es/colombia/medicamento/1537735/diuxoton-20-mg-ml-sol-iny-)
[DESMOPRESINA ACETATO MEDYSEH LTDA. 15 mcg/1 ml Sol. iny.](https://www.vademecum.es/colombia/medicamento/1571937/desmopresina-acetato-medyseh-ltda-15-mcg-1-ml-sol-iny-)
[DEXAMETASONA BIOSANO 8 mg/2 ml Sol. iny.](https://www.vademecum.es/colombia/medicamento/1537891/dexametasona-biosano-8-mg-2-ml-sol-iny-)
[EPOYET 10000 UI Liof. para sol. iny.](https://www.vademecum.es/colombia/medicamento/1559419/epoyet-10000-ui-liof-para-sol-iny-)
[EPAMIN PARENTERICO 50 mg/ml Sol. iny.](https://www.vademecum.es/colombia/medicamento/1549231/epamin-parenterico-50-mg-ml-sol-iny-)
[ERITROMAX 2000 UI/1 ml Sol. iny.](https://www.vademecum.es/colombia/medicamento/1559415/eritromax-2000-ui-1-ml-sol-iny-)
[ERITROMICINA  MK 500 mg Comp. recub.](https://www.vademecum.es/colombia/medicamento/1537489/eritromicina-mk-500-mg-comp-recub-)
[EPCLUSA 400 mg/100 mg Tab. recubierta](https://www.vademecum.es/colombia/medicamento/1537516/epclusa-400-mg-100-mg-tab-recubierta)
[EPIBALIN 150 mg Cáps. dura](https://www.vademecum.es/colombia/medicamento/1571607/epibalin-150-mg-caps-dura-)
[FUZEON POLVO SOLUCION INYECTABLE 90 mg Liof. para sol. iny.](https://www.vademecum.es/colombia/medicamento/1537024/fuzeon-polvo-solucion-inyectable-90-mg-liof-para-sol-iny-)
[FYBOGEL Gránulos](https://www.vademecum.es/colombia/medicamento/1557110/fybogel-granulos)
[FUROSEMIDA  MK 40 mg Tab.](https://www.vademecum.es/colombia/medicamento/1537033/furosemida-mk-40-mg-tab-)
[FRAGMIN 7500 UI Sol. iny.](https://www.vademecum.es/colombia/medicamento/1537078/fragmin-7500-ui-sol-iny-)
[FRAXIPARINE 2850 U/0,3 ml Sol. iny.](https://www.vademecum.es/colombia/medicamento/1571454/fraxiparine-2850-u-0-3-ml-sol-iny-en-jeringa-precargada)
[FOSTRAMAR 3 g/1 sobre Polvo para sol. oral](https://www.vademecum.es/colombia/medicamento/1537080/fostramar-3-g-1-sobre-polvo-para-sol-oral-)
[FOTORRETIN 0,5 %/5 % Sol. oftálmica](https://www.vademecum.es/colombia/medicamento/1557115/fotorretin-0-5-5-sol-oftalmica)
[FOVIREM 200 mg/300 mg Comp. Recub.](https://www.vademecum.es/colombia/medicamento/1561519/fovirem-200-mg-300-mg-comp-recub-)
[GEFBOOK 250 mg Tab. recub.](https://www.vademecum.es/colombia/medicamento/1625633/gefbook-250-mg-tab-recub-)
[GEFINEX 250 mg Tab. recubierta](https://www.vademecum.es/colombia/medicamento/1549163/gefinex-250-mg-tab-recubierta)
[GELNIDA 3 % Gel dérmico](https://www.vademecum.es/colombia/medicamento/1560240/gelnida-3-gel-dermico)
[GELOFUSINE ISO 4 % Sol. iny.](https://www.vademecum.es/colombia/medicamento/1559104/gelofusine-iso-4-sol-iny-)
[GELPIN 50 mg Cáps. blanda](https://www.vademecum.es/colombia/medicamento/1536967/gelpin-50-mg-caps-blanda)
[GEMCITABINA 1000 mg Liof. para sol. iny.](https://www.vademecum.es/colombia/medicamento/1536963/gemcitabina-1000-mg-liof-para-sol-iny-)
[GEMCOVAC-OM VAXTHERA 10 mcg Liof. para sol. iny.](https://www.vademecum.es/colombia/medicamento/1616086/gemcovac-om-vaxthera-10-mcg-liof-para-sol-iny-)
[HISTAFLEX JARABE 0,1 g/0,05 g/100 ml Jarabe](https://www.vademecum.es/colombia/medicamento/1536739/histaflex-jarabe-0-1-g-0-05-g-100-ml-jarabe)
[HISTAIR 5 mg Tab. recubierta](https://www.vademecum.es/colombia/medicamento/1536737/histair-5-mg-tab-recubierta)
[HISTIVERT 16 mg Tab.](https://www.vademecum.es/colombia/medicamento/1559633/histivert-16-mg-tab-)
[HISTOTAL 25000 UI Sol. oral](https://www.vademecum.es/colombia/medicamento/1536735/histotal-25000-ui-sol-oral)
[HIZENTRA 1 g/5 ml Sol. iny.](https://www.vademecum.es/colombia/medicamento/1616082/hizentra-1-g-5-ml-sol-iny-)
[HOGAM 300 mcg/1 ml](https://www.vademecum.es/colombia/medicamento/1559632/hogam-300-mcg-1-ml-sol-iny-en-jeringa-precargada)
[HOLMES 20 mg Tab. recubierta](https://www.vademecum.es/colombia/medicamento/1559631/holmes-20-mg-tab-recubierta)
[HOLOXAN 2 g Polvo para sol. iny.](https://www.vademecum.es/colombia/medicamento/1536732/holoxan-2-g-polvo-para-sol-iny-)
[IPCA RAMCOR 5 mg Cáps. dura](https://www.vademecum.es/colombia/medicamento/1536583/ipca-ramcor-5-mg-caps-dura)
[IPICLAV 875 mg/125 mg Tab. recubierta](https://www.vademecum.es/colombia/medicamento/1536582/ipiclav-875-mg-125-mg-tab-recubierta)
[IPIPRAL 15 mg Tab.](https://www.vademecum.es/colombia/medicamento/1536580/ipipral-15-mg-tab-)
[IPOPRIN 2 mg Cáps. dura](https://www.vademecum.es/colombia/medicamento/1536577/ipoprin-2-mg-caps-dura)
[IPRASYNT 0,021 mg Aerosol](https://www.vademecum.es/colombia/medicamento/1536576/iprasynt-0,021-mg-aerosol)
[IRBEPREX 150 mg Tab.](https://www.vademecum.es/colombia/medicamento/1536575/irbeprex-150-mg-tab-)
[JARABE VICKMIEL 1,6 g/100 ml Jarabe](https://www.vademecum.es/colombia/medicamento/1536502/jarabe-vickmiel-1-6-g-100-ml-jarabe)
[JARDIANCE 10 mg Tab. recubierta](https://www.vademecum.es/colombia/medicamento/1536501/jardiance-10-mg-tab-recubierta)
[KETOPROFENO GENFAR 100 mg](https://www.vademecum.es/colombia/medicamento/1536436/ketoprofeno-genfar-100-mg-tab-recubierta)
[KETESSE 25 mg Tab. recubierta](https://www.vademecum.es/colombia/medicamento/1557258/ketesse-25-mg-tab-recubierta)
[KERADOL 10 mg Tab. recubierta](https://www.vademecum.es/colombia/medicamento/1536453/keradol-tabletas-recubiertas-10-mg-tab-recubierta)
[KESIMPTA 50 mg/1 ml Sol. iny.](https://www.vademecum.es/colombia/medicamento/1549079/kesimpta-50-mg-1-ml-sol-iny-en-pluma-precargada)
[KESOFER 20 mg/ml Champú](https://www.vademecum.es/colombia/medicamento/1625876/kesofer-20-mg-ml-champu)
[KENALER - R 0,25 mg/ml Sol. oftálmica](https://www.vademecum.es/colombia/medicamento/1536461/kenaler-r-0-25-mg-ml-sol-oftalmica)
[KEPERTAN 100 mg/ml Sol. oral.](https://www.vademecum.es/colombia/medicamento/1625877/kepertan-100-mg-ml-sol-oral-)
[LESTYNA 2,5 mg/20 mg Cáps. dura](https://www.vademecum.es/colombia/medicamento/1536304/lestyna-capsulas-2-5-mg-20-mg-caps-dura)
[LET 2,5 mg Tab. recubierta](https://www.vademecum.es/colombia/medicamento/1536303/let-2-5-mg-tab-recubierta)
[LETROZOL 2,5 mg Tab. recubierta](https://www.vademecum.es/colombia/medicamento/1549044/letrozol-2-5-mg-tab-recubierta)
[LEUCOMIDA 15 mg Cáps.](https://www.vademecum.es/colombia/medicamento/1625949/leucomida-15-mg-caps-)
[LEUCO-SCINT 18 mg Liof. para sol. iny.](https://www.vademecum.es/colombia/medicamento/1549043/leuco-scint-18-mg-liof-para-sol-iny-)
[LEUKERAN 2 mg Tab. recubierta](https://www.vademecum.es/colombia/medicamento/1536301/leukeran-tabletas-recubiertas-2-mg-tab-recubierta)
[LEUKUSTIM 100 mg Liof. para sol. iny.](https://www.vademecum.es/colombia/medicamento/1536300/leukustim-100-mg-liof-para-sol-iny-)
[MIDAZOLAM  VITALIS 50 mg/10 ml](https://www.vademecum.es/colombia/medicamento/1535884/midazolam-vitalis-50-mg-10-ml-sol-iny-)
[METOCLOPRAMIDA RYAN 10 mg Sol. iny.](https://www.vademecum.es/colombia/medicamento/1535956/metoclopramida-ryan-10-mg-sol-iny-)
[METOJECT 7,5 mg/0,15 ml Sol. iny.](https://www.vademecum.es/colombia/medicamento/1558451/metoject-7-5-mg-0-15-ml-sol-iny-en-jeringa-precargada)
[MIDUFARKO 5 mg/ml Sol. iny.](https://www.vademecum.es/colombia/medicamento/1626307/midufarko-5-mg-ml-sol-iny-)
[MIELOZITIDINA Polvo liof.](https://www.vademecum.es/colombia/medicamento/1559327/mielozitidina-polvo-liof-)
[MIRCERA 100 mcg/0,3 ml Sol. iny.](https://www.vademecum.es/colombia/medicamento/1535841/mircera-solucion-inyectable-jeringa-prellenada-100-mcg-0-3-ml-sol-iny-)
[METHERGIN 0,2 mg/1 ml Sol. Iny.](https://www.vademecum.es/colombia/medicamento/1558334/methergin-0-2-mg-1-ml-sol-iny-)
[MIOACTINE 100 mg/1 ml Sol. iny.](https://www.vademecum.es/colombia/medicamento/1535853/mioactine-100-mg-1-ml-sol-iny-)
[MUVETT 50 mg/5 ml Sol. Iny.](https://www.vademecum.es/colombia/medicamento/1535754/muvett-inyectable-50-mg-5-ml-sol-iny-)
[NOXPIRIN Cáps. dura](https://www.vademecum.es/colombia/medicamento/1556503/noxpirin-caps-dura)
[NOZOMI 50 mg Liof. para sol. iny.](https://www.vademecum.es/colombia/medicamento/1535513/nozomi-50-mg-liof-para-sol-iny-)
[NPLATE 250 mcg Liof. para sol. iny.](https://www.vademecum.es/colombia/medicamento/1535512/nplate-250-mcg-liof-para-sol-iny-)
[NUBEQA 300 mg Tab. recubierta](https://www.vademecum.es/colombia/medicamento/1535511/nubeqa-300-mg-tab-recubierta)
[NUCALA 100 mg Polvo para sol. iny.](https://www.vademecum.es/colombia/medicamento/1535510/nucala-100-mg-polvo-para-sol-iny-)
[NUCLEVIT FOL 70 mg/0,4 mg/60 mg](https://www.vademecum.es/colombia/medicamento/1535508/nuclevit-fol-70-mg-0-4-mg-60-mg-tab-recubierta)
[NUCTIS D 5600 UI/1 ml Sol. oral](https://www.vademecum.es/colombia/medicamento/1535507/nuctis-dgotas-orales-5600-ui-1-ml-sol-oral)
[NUEVID 7000 UI Tab. recubierta](https://www.vademecum.es/colombia/medicamento/1535506/nuevid-7000-ui-tab-recubierta)
[OPHTHABRACIN-D 0,1 g/0,3 g/100 g Ung.](https://www.vademecum.es/colombia/medicamento/1535381/ophthabracin-d-unguento-0-1-g-0-3-g-100-g-ung-oftalmico-)
[OPHTHAKER 5 mg/ml Sol. oftálmica](https://www.vademecum.es/colombia/medicamento/1535380/ophthaker-5-mg-ml-sol-oftalmica)
[OPHTHASONA 1 mg/1 ml Sol. oftálmica](https://www.vademecum.es/colombia/medicamento/1558617/ophthasona-1-mg-1-ml-sol-oftalmica-)
[OPPTEST HB 5 mg Tab. recubierta](https://www.vademecum.es/colombia/medicamento/1558616/opptest-hb-5-mg-tab-recubierta)
[OPSUMIT 10 mg Tab. recubierta](https://www.vademecum.es/colombia/medicamento/1535379/opsumit-10-mg-tab-recubierta)
[OPTI COMFORT 10 mg/2 mg/1 ml](https://www.vademecum.es/colombia/medicamento/1558615/opti-comfort-10-mg-2-mg-1-ml-sol-oftalmica-)
[OPTIALIV 3 mg/ml Sol. oftálmica](https://www.vademecum.es/colombia/medicamento/1535378/optialiv-gotas-lubricantes-3-mg-ml-sol-oftalmica-)
[OPTICAM 3 mg/1 ml Sol. oftálmica](https://www.vademecum.es/colombia/medicamento/1535377/opticam-3-mg-1-ml-sol-oftalmica)
[OPTIRAY 300 636 mg/1 ml Sol. iny.](https://www.vademecum.es/colombia/medicamento/1558614/optiray-300-636-mg-1-ml-sol-iny-)
[PARKEN 25 mg/100 mg Tab.](https://www.vademecum.es/colombia/medicamento/1556487/parken-25-mg-100-mg-tab-)
[PARMODOL 1000 mg/100 ml Sol. iny.](https://www.vademecum.es/colombia/medicamento/1535245/parmodol-solucion-inyectable-1000-mg-100-ml-sol-iny-)
[PAROLEX 50 mg Tab. recubierta](https://www.vademecum.es/colombia/medicamento/1535244/parolex-50-mg-tab-recubierta)
[PAROXETINA  GENFAR 20 mg](https://www.vademecum.es/colombia/medicamento/1535241/paroxetina-genfar-20-mg-tab-recubierta)
[PASEDOL 50 mg Tab.](https://www.vademecum.es/colombia/medicamento/1556588/pasedol-50-mg-tab-)
[PASMIROL 50 mg Tab.](https://www.vademecum.es/colombia/medicamento/1559595/pasmirol-50-mg-tab-)
[PASTA AL AGUA ALMIPRO 25 g/100 g](https://www.vademecum.es/colombia/medicamento/1535239/pasta-al-agua-almipro-25-g-100-g-pasta)
[PATALER I 2 mg/ml Sol. oftálmica](https://www.vademecum.es/colombia/medicamento/1556587/pataler-i-2-mg-ml-sol-oftalmica)
[PAX CALIENTE NOCHE 2 mg/10 mg/500 mg](https://www.vademecum.es/colombia/medicamento/1535236/pax-caliente-noche-granulado-sabora-panela-limon-y-sabor-a-limon-2-mg-10-mg-500-mg-1-sobre-granulos)
[QUIMOX 5 mg/ml Sol. oftálmica](https://www.vademecum.es/colombia/medicamento/1534971/quimox-5-mg-ml-sol-oftalmica)
[QUINAPRIL 20 mg Tab. recubierta](https://www.vademecum.es/colombia/medicamento/1556485/quinapril-tecnoquimicas-20-mg-tab-recubierta)
[QUINOMAX 400 mg Tab. recubierta](https://www.vademecum.es/colombia/medicamento/1534970/quinomax-400-mg-tab-recubierta)
[RINOLAST D 25 mg/60 mg Tab. recub.](https://www.vademecum.es/colombia/medicamento/1534850/rinolast-d-tabletas-recubiertas-25-mg-60-mg-tab-recubierta)
[RINOSONA 0,05 g/100 ml Susp. nasal](https://www.vademecum.es/colombia/medicamento/1534848/rinosona-0-05-g-100-ml-susp-nasal)
[RINOTADIN 5 mg Tab. recubierta](https://www.vademecum.es/colombia/medicamento/1559581/rinotadin-5-mg-tab-recubierta)
[RINVOQ 15 mg Comp. LP](https://www.vademecum.es/colombia/medicamento/1534847/rinvoq-15-mg-comp-lp)
[RIOCI 0,5 mg Tab. recub.](https://www.vademecum.es/colombia/medicamento/1625614/rioci-0-5-mg-tab-recub-)
[RIOPAN 8 g/1 g Gel oral](https://www.vademecum.es/colombia/medicamento/1556476/riopan-8-g-1-g-gel-oral)
[RISNIA 1 mg Tab.](https://www.vademecum.es/colombia/medicamento/1571676/risnia-1-mg-tab-)
[SIGNIFOR LAR 20 mg Polvo para susp.](https://www.vademecum.es/colombia/medicamento/1558917/signifor-lar-20-mg-polvo-para-susp-iny-)
[SIKLOS 100 mg Tab. recubierta](https://www.vademecum.es/colombia/medicamento/1571546/siklos-100-mg-tab-recubierta)
[SIL - NORBORAL 5 mg/1000 mg](https://www.vademecum.es/colombia/medicamento/1534635/sil-norboral-5-mg-1000-mg-tab-recubierta)
[SILDENAFIL 100 mg Tab. recubierta](https://www.vademecum.es/colombia/medicamento/1559273/sildenafil-100-mg-tab-recubierta)
[TIMOGLOBULINA 25 mg Liof.](https://www.vademecum.es/colombia/medicamento/1559788/timoglobulina-25-mg-liof-para-sol-iny-)
[TIMOLOL  MK 5 mg/1 ml Sol. oftálmica](https://www.vademecum.es/colombia/medicamento/1534236/timolol-mk-5-mg-1-ml-sol-oftalmica)
[TINIDAZOL  MEMPHIS 500 mg](https://www.vademecum.es/colombia/medicamento/1534231/tinidazol-memphis-500-mg-tab-recubierta)
[UPGLYCEM 5 g/100 ml Susp. oral](https://www.vademecum.es/colombia/medicamento/1534009/upglycem-5-g-100-ml-susp-oral)
[UPLIZNA 10 mg/1 ml](https://www.vademecum.es/colombia/medicamento/1571405/uplizna-10-mg-1-ml-concentr-para-sol-para-infus-)
[UPTRAVI 200 mcg Tab. recubierta](https://www.vademecum.es/colombia/medicamento/1548697/uptravi-200-mcg-tab-recubierta)
[URALGIC 400 mg Tab. recubierta](https://www.vademecum.es/colombia/medicamento/1534008/uralgic-400-mg-tab-recubierta)
[UREADERM 15 g/100 g Crema tópica](https://www.vademecum.es/colombia/medicamento/1534004/ureaderm-15-g-100-g-crema-topica)
[UREXIL 80 mg Tab. recubierta](https://www.vademecum.es/colombia/medicamento/1534002/urexil-80-mg-tab-recubierta)
[URITOS 0,1 mg Tab. recubierta](https://www.vademecum.es/colombia/medicamento/1571118/uritos-0-1-mg-tab-recubierta)
[VENLAFAXINA TQ 75 mg Tab. LP](https://www.vademecum.es/colombia/medicamento/1533897/venlafaxina-tq-75-mg-tab-lp)
[VENLAVITAE 75 mg Cáps. LP](https://www.vademecum.es/colombia/medicamento/1571400/venlavitae-75-mg-caps-lp)
[VENOFER 100 mg/5 ml Sol. iny.](https://www.vademecum.es/colombia/medicamento/1548675/venofer-100-mg-5-ml-sol-iny-)
[VENOSMIL 200 mg Cáps.](https://www.vademecum.es/colombia/medicamento/1533895/venosmil-capsula-200-mg-caps-)
[VENTILAN 100 mcg/dosis Susp. inhal.](https://www.vademecum.es/colombia/medicamento/1533892/ventilan-osp-inhalador-100-mcg-dosis-susp-inhal-)
[VERACEF 500 mg Cáps.](https://www.vademecum.es/colombia/medicamento/1533891/veracef-capsulas-500-mg-caps-)
[WINADEINE F 30 mg/325 mg Tab.](https://www.vademecum.es/colombia/medicamento/1533738/winadeine-f-30-mg-325-mg-tab-)
[XELODA 500 mg Comp. recub.](https://www.vademecum.es/colombia/medicamento/1533715/xeloda-tabletas-lacadas-500-mg-comp-recub-)
[XENICAL 120 mg Cáps. dura](https://www.vademecum.es/colombia/medicamento/1533714/xenical-capsulas-120-mg-caps-dura)
[XEOMIN 100 U Liof. para sol. iny.](https://www.vademecum.es/colombia/medicamento/1533713/xeomin-100-u-liof-para-sol-iny-)
[YAEL 2 mg/0,03 mg](https://www.vademecum.es/colombia/medicamento/1533695/yael-2-mg-0-03-mg-tab-recubierta)
[YODINFEX 10 g/100 ml Sol. tópica](https://www.vademecum.es/colombia/medicamento/1533688/yodinfex-solucion-topica-10-g-100-ml-sol-topica)
[ZOLPIDEM TQ 10 mg Tab. recubierta](https://www.vademecum.es/colombia/medicamento/1533619/zolpidem-tq-10-mg-tab-recubierta)
[ZOPICLONA  MK 7,5 mg](https://www.vademecum.es/colombia/medicamento/1533612/zopiclona-mk-7-5-mg-tab-recubierta)
"""

# Limpiar y extraer
pattern = r'\[(.*?)\]\((.*?)\)'
matches = re.findall(pattern, raw_data)

results = []
seen_generics = set()

# Suffixes extendidos
lab_suffixes = r'(?i)\s+(GENFAR|MK|TECNOQUÍMICAS|VITALIS|PROCAPS|FARMALOGICA|EUGIA|MK|NORTH CHINA|PUNISKA|AMERICAN GENERICS|PENTACOOP|BIOSANO|SANDERSON|TECNIQUIMICAS|TQ|FRESENIUS KABI|HUMAX|ROSSBLANK|VITALIS|MEGALABS|EUROFARMA|ABBVIE|EUCALIPTO|LICOL|RYAN|COLMED|COFAREN|BIO ESTERIL|MEDYSEH|UNIPHARM|BLAU|VENUS|VAXTHERA|ROPSOHN|PATMAR|BLUEPHARMA|LA SANTÉ|MEMPHIS|ECAR|LAPROFF|BUSSIE|RICHMOND|PATOTAS|AVT|QUIFARMA|ALMIPRO|VICKMIEL|MERCK|BAYER|PFIZER|NOVARTIS|SANOFI|ROCHE|GLAXO|GSK|NORTHWAY|NORTHSTAY|NORTHCHINA|NORTHWEST).*'

for label, url in matches:
    clean_label = re.sub(lab_suffixes, '', label)
    generic_name = re.sub(r'\s+\d+.*', '', clean_label).strip()
    
    # Normalización simple
    generic_name = generic_name.upper().replace('  ', ' ')
    
    if generic_name not in seen_generics and len(generic_name) > 3:
        results.append({
            'label': label,
            'generic_name': generic_name,
            'url': url
        })
        seen_generics.add(generic_name)

# Guardar lista de objetivos
with open('med_targets.json', 'w', encoding='utf-8') as f:
    json.dump(results, f, indent=2, ensure_ascii=False)

print(f"Encontrados {len(results)} genéricos únicos para extraer.")
